<x-mail::message>
# Scheduled Export Ready

Your scheduled export **{{ $exportName }}** for module **{{ $module }}** is attached to this email.

| Detail | Information |
|---|---|
| Export | {{ $exportName }} |
| Module | {{ $module }} |
| File | {{ $filename }} |
| Format | {{ $format }} |

The attached file was generated by {{ config('mail.from.name', 'Ogami Philippines') }}.

Thanks,<br>
{{ config('mail.from.name', 'Ogami Philippines') }}
</x-mail::message>
