/**
 * The application's icon boundary.
 *
 * Tabler Icons replaces the previous Lucide-via-react-icons set. The aliases
 * below keep the migration reviewable while allowing every surface to share
 * one typed, outline icon language. Feature-specific choices intentionally
 * use Tabler's more precise concepts (for example factory, delivery, invoice,
 * warehouse package, and quality icons).
 */
import {
  IconActivity as LuActivity,
  IconArchive as LuArchive,
  IconArchive as LuArchiveRestore,
  IconArrowDown as LuArrowDown,
  IconArrowLeft as LuArrowLeft,
  IconArrowsLeftRight as LuArrowLeftRight,
  IconArrowRight as LuArrowRight,
  IconArrowUp as LuArrowUp,
  IconAward as LuAward,
  IconRosetteDiscountCheck as LuBadgeCheck,
  IconBan as LuBan,
  IconCashBanknote as LuBanknote,
  IconFlask as LuBeaker,
  IconBell as LuBell,
  IconBellOff as LuBellOff,
  IconBellRinging as LuBellRing,
  IconBook as LuBookOpen,
  IconBox as LuBox,
  IconPackages as LuBoxes,
  IconBriefcase as LuBriefcase,
  IconBuilding as LuBuilding2,
  IconCalendar as LuCalendar,
  IconCalendarClock as LuCalendarClock,
  IconCalendar as LuCalendarDays,
  IconCalendarWeek as LuCalendarRange,
  IconCamera as LuCamera,
  IconCar as LuCar,
  IconChartColumn as LuChartColumn,
  IconChartLine as LuChartColumnIncreasing,
  IconChartPie as LuChartPie,
  IconCheck as LuCheck,
  IconChecks as LuCheckCheck,
  IconChevronDown as LuChevronDown,
  IconChevronLeft as LuChevronLeft,
  IconChevronRight as LuChevronRight,
  IconChevronsLeft as LuChevronsLeft,
  IconChevronsRight as LuChevronsRight,
  IconCircle as LuCircle,
  IconAlertCircle as LuCircleAlert,
  IconCircleCheck as LuCircleCheck,
  IconCurrencyDollar as LuCircleDollarSign,
  IconCircleDot as LuCircleDot,
  IconHelpCircle as LuCircleHelp,
  IconCircleMinus as LuCircleMinus,
  IconPlayerPause as LuCirclePause,
  IconCirclePlus as LuCirclePlus,
  IconPlayerStop as LuCircleStop,
  IconCircleX as LuCircleX,
  IconClipboard as LuClipboard,
  IconClipboardCheck as LuClipboardCheck,
  IconClipboardList as LuClipboardList,
  IconClock as LuClock,
  IconClock as LuClock3,
  IconClock as LuClock4,
  IconCloudUpload as LuCloudUpload,
  IconSettings as LuCog,
  IconCoins as LuCoins,
  IconCopy as LuCopy,
  IconCpu as LuCpu,
  IconDatabase as LuDatabase,
  IconCurrencyDollar as LuDollarSign,
  IconDownload as LuDownload,
  IconDroplets as LuDroplets,
  IconExternalLink as LuExternalLink,
  IconEye as LuEye,
  IconEyeOff as LuEyeOff,
  IconBuildingFactory as LuFactory,
  IconFileCheck as LuFileCheck2,
  IconFileDownload as LuFileDown,
  IconFilePencil as LuFilePen,
  IconFilePencil as LuFilePenLine,
  IconFileInfo as LuFileQuestion,
  IconFileText as LuFileText,
  IconFileAlert as LuFileWarning,
  IconFileX as LuFileX,
  IconFolderOpen as LuFolderOpen,
  IconGauge as LuGauge,
  IconGitBranch as LuGitBranch,
  IconGitCompare as LuGitCompareArrows,
  IconGitFork as LuGitFork,
  IconSchool as LuGraduationCap,
  IconGrid3x3 as LuGrid3X3,
  IconGripVertical as LuGripVertical,
  IconHammer as LuHammer,
  IconHandClick as LuHand,
  IconMoneybag as LuHandCoins,
  IconPhoto as LuImage,
  IconInbox as LuInbox,
  IconInfoCircle as LuInfo,
  IconKey as LuKey,
  IconKey as LuKeyRound,
  IconBuildingBank as LuLandmark,
  IconStack as LuLayers,
  IconLayoutDashboard as LuLayoutDashboard,
  IconLayoutGrid as LuLayoutGrid,
  IconLink as LuLink2,
  IconList as LuList,
  IconListCheck as LuListChecks,
  IconListTree as LuListTree,
  IconLoader as LuLoader,
  IconLoader2 as LuLoaderCircle,
  IconLock as LuLock,
  IconLockOpen as LuLockOpen,
  IconLogin as LuLogIn,
  IconLogout as LuLogOut,
  IconMail as LuMail,
  IconMailOpened as LuMailOpen,
  IconMapPin as LuMapPin,
  IconMenu as LuMenu,
  IconMessage as LuMessageSquare,
  IconMinus as LuMinus,
  IconDeviceDesktop as LuMonitor,
  IconMoon as LuMoon,
  IconNavigation as LuNavigation,
  IconPackage as LuPackage,
  IconPackageImport as LuPackageCheck,
  IconPlayerPause as LuPause,
  IconPencil as LuPencil,
  IconPercentage as LuPercent,
  IconPhone as LuPhone,
  IconPlayerPlay as LuPlay,
  IconPlus as LuPlus,
  IconPrinter as LuPrinter,
  IconPuzzle as LuPuzzle,
  IconReceipt as LuReceipt,
  IconFileInvoice as LuReceiptText,
  IconRefresh as LuRefreshCw,
  IconArrowBackUp as LuRotateCcw,
  IconRoute as LuRoute,
  IconLayoutRows as LuRows2,
  IconLayoutRows as LuRows3,
  IconLayoutRows as LuRows4,
  IconRulerMeasure as LuRuler,
  IconDeviceFloppy as LuSave,
  IconScale as LuScale,
  IconBarcode as LuScanBarcode,
  IconScan as LuScanLine,
  IconSearch as LuSearch,
  IconSearchOff as LuSearchX,
  IconSend as LuSend,
  IconServer as LuServer,
  IconSettings as LuSettings,
  IconSettings2 as LuSettings2,
  IconShield as LuShield,
  IconShieldExclamation as LuShieldAlert,
  IconShieldCheck as LuShieldCheck,
  IconShoppingCart as LuShoppingCart,
  IconAdjustmentsHorizontal as LuSlidersHorizontal,
  IconDeviceMobile as LuSmartphone,
  IconSparkles as LuSparkles,
  IconSquare as LuSquare,
  IconSquareCheck as LuSquareCheck,
  IconStar as LuStar,
  IconStarOff as LuStarOff,
  IconStethoscope as LuStethoscope,
  IconNote as LuStickyNote,
  IconBuildingStore as LuStore,
  IconSun as LuSun,
  IconTag as LuTag,
  IconTarget as LuTarget,
  IconThermometer as LuThermometer,
  IconThumbDown as LuThumbsDown,
  IconThumbUp as LuThumbsUp,
  IconStopwatch as LuTimer,
  IconTrash as LuTrash2,
  IconTrendingDown as LuTrendingDown,
  IconTrendingUp as LuTrendingUp,
  IconAlertTriangle as LuTriangleAlert,
  IconTruckDelivery as LuTruck,
  IconArrowBack as LuUndo2,
  IconUpload as LuUpload,
  IconUser as LuUser,
  IconUserCheck as LuUserCheck,
  IconUserMinus as LuUserMinus,
  IconUserPlus as LuUserPlus,
  IconUserX as LuUserX,
  IconUsers as LuUsers,
  IconWallet as LuWallet,
  IconWifiOff as LuWifiOff,
  IconGitBranch as LuWorkflow,
  IconTool as LuWrench,
  IconBolt as LuZap,
  IconX as LuX,
} from "@tabler/icons-react";

export type { TablerIcon as IconType } from "@tabler/icons-react";

/**
 * Semantic names for navigation and feature metadata. New surfaces should use
 * these names; the Lu* exports below remain only as a low-risk migration bridge
 * for the existing page-level controls.
 */
export {
  IconLayoutDashboard as DashboardIcon,
  IconTopologyStar3 as WorkflowIcon,
  IconShoppingCart as OrderIcon,
  IconFilePlus as RequestIcon,
  IconFileInvoice as InvoiceIcon,
  IconReceipt2 as BillIcon,
  IconTruckDelivery as DeliveryIcon,
  IconCalendarClock as ScheduleIcon,
  IconClipboardList as WorkOrderIcon,
  IconPackageImport as ReceivingIcon,
  IconPackageExport as IssuanceIcon,
  IconPackages as InventoryIcon,
  IconPackage as PickingIcon,
  IconMap as WarehouseMapIcon,
  IconClipboardCheck as InspectionIcon,
  IconMessageReport as ComplaintIcon,
  IconTruckReturn as ReturnIcon,
  IconFileDollar as PriceAgreementIcon,
  IconSteeringWheel as FleetIcon,
  IconReceiptRefund as CreditNoteIcon,
} from "@tabler/icons-react";

export {
  LuActivity,
  LuArchive,
  LuArchiveRestore,
  LuArrowDown,
  LuArrowLeft,
  LuArrowLeftRight,
  LuArrowRight,
  LuArrowUp,
  LuAward,
  LuBadgeCheck,
  LuBan,
  LuBanknote,
  LuBeaker,
  LuBell,
  LuBellOff,
  LuBellRing,
  LuBookOpen,
  LuBox,
  LuBoxes,
  LuBriefcase,
  LuBuilding2,
  LuCalendar,
  LuCalendarClock,
  LuCalendarDays,
  LuCalendarRange,
  LuCamera,
  LuCar,
  LuChartColumn,
  LuChartColumnIncreasing,
  LuChartPie,
  LuCheck,
  LuCheckCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronsLeft,
  LuChevronsRight,
  LuCircle,
  LuCircleAlert,
  LuCircleCheck,
  LuCircleDollarSign,
  LuCircleDot,
  LuCircleHelp,
  LuCircleMinus,
  LuCirclePause,
  LuCirclePlus,
  LuCircleStop,
  LuCircleX,
  LuClipboard,
  LuClipboardCheck,
  LuClipboardList,
  LuClock,
  LuClock3,
  LuClock4,
  LuCloudUpload,
  LuCog,
  LuCoins,
  LuCopy,
  LuCpu,
  LuDatabase,
  LuDollarSign,
  LuDownload,
  LuDroplets,
  LuExternalLink,
  LuEye,
  LuEyeOff,
  LuFactory,
  LuFileCheck2,
  LuFileDown,
  LuFilePen,
  LuFilePenLine,
  LuFileQuestion,
  LuFileText,
  LuFileWarning,
  LuFileX,
  LuFolderOpen,
  LuGauge,
  LuGitBranch,
  LuGitCompareArrows,
  LuGitFork,
  LuGraduationCap,
  LuGrid3X3,
  LuGripVertical,
  LuHammer,
  LuHand,
  LuHandCoins,
  LuImage,
  LuInbox,
  LuInfo,
  LuKey,
  LuKeyRound,
  LuLandmark,
  LuLayers,
  LuLayoutDashboard,
  LuLayoutGrid,
  LuLink2,
  LuList,
  LuListChecks,
  LuListTree,
  LuLoader,
  LuLoaderCircle,
  LuLock,
  LuLockOpen,
  LuLogIn,
  LuLogOut,
  LuMail,
  LuMailOpen,
  LuMapPin,
  LuMenu,
  LuMessageSquare,
  LuMinus,
  LuMonitor,
  LuMoon,
  LuNavigation,
  LuPackage,
  LuPackageCheck,
  LuPause,
  LuPencil,
  LuPercent,
  LuPhone,
  LuPlay,
  LuPlus,
  LuPrinter,
  LuPuzzle,
  LuReceipt,
  LuReceiptText,
  LuRefreshCw,
  LuRotateCcw,
  LuRoute,
  LuRows2,
  LuRows3,
  LuRows4,
  LuRuler,
  LuSave,
  LuScale,
  LuScanBarcode,
  LuScanLine,
  LuSearch,
  LuSearchX,
  LuSend,
  LuServer,
  LuSettings,
  LuSettings2,
  LuShield,
  LuShieldAlert,
  LuShieldCheck,
  LuShoppingCart,
  LuSlidersHorizontal,
  LuSmartphone,
  LuSparkles,
  LuSquare,
  LuSquareCheck,
  LuStar,
  LuStarOff,
  LuStethoscope,
  LuStickyNote,
  LuStore,
  LuSun,
  LuTag,
  LuTarget,
  LuThermometer,
  LuThumbsDown,
  LuThumbsUp,
  LuTimer,
  LuTrash2,
  LuTrendingDown,
  LuTrendingUp,
  LuTriangleAlert,
  LuTruck,
  LuUndo2,
  LuUpload,
  LuUser,
  LuUserCheck,
  LuUserMinus,
  LuUserPlus,
  LuUserX,
  LuUsers,
  LuWallet,
  LuWifiOff,
  LuWorkflow,
  LuWrench,
  LuZap,
  LuX,
};
