<?php

declare(strict_types=1);

namespace App\Modules\Admin\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UpdateSettingRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()?->can('admin.settings.manage') ?? false;
    }

    public function rules(): array
    {
        $key = $this->route('key');

        $base = ['value' => ['present']];

        $securityRules = [
            'security.max_login_attempts'      => ['value' => ['required', 'integer', 'min:1', 'max:20']],
            'security.lockout_minutes'          => ['value' => ['required', 'integer', 'min:1', 'max:60']],
            'security.password_history_depth'   => ['value' => ['required', 'integer', 'min:0', 'max:10']],
            'security.password_min_length'      => ['value' => ['required', 'integer', 'min:6', 'max:32']],
            'security.session_timeout_employee' => ['value' => ['required', 'integer', 'min:5', 'max:120']],
            'security.session_timeout_default'  => ['value' => ['required', 'integer', 'min:5', 'max:120']],
            'security.password_expiry_days'     => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'security.password_reset_expiry_minutes' => ['value' => ['required', 'integer', 'min:5', 'max:10080']],
        ];

        $maintenanceRules = [
            'maintenance.predictive.temperature.max' => ['value' => ['required', 'numeric', 'min:0']],
            'maintenance.predictive.vibration.max'   => ['value' => ['required', 'numeric', 'min:0']],
            'maintenance.predictive.pressure.min'    => ['value' => ['required', 'numeric', 'min:0']],
            'maintenance.predictive.pressure.max'    => ['value' => ['required', 'numeric', 'min:0']],
            'maintenance.predictive.current.max'     => ['value' => ['required', 'numeric', 'min:0']],
            'maintenance.predictive.oil_quality.min' => ['value' => ['required', 'numeric', 'min:0', 'max:100']],
            'maintenance.predictive.metrics' => ['value' => ['required', 'array', 'min:1']],
            'maintenance.predictive.sources' => ['value' => ['required', 'array', 'min:1']],
            'maintenance.predictive.default_source' => ['value' => ['required', 'string', 'max:30']],
            'maintenance.predictive.breach_window'   => ['value' => ['required', 'integer', 'min:1', 'max:20']],
        ];

        if (str_starts_with((string) $key, 'loans.') && str_ends_with((string) $key, '.annual_interest_rate')) {
            return ['value' => ['required', 'numeric', 'min:0', 'max:1']];
        }
        if (str_starts_with((string) $key, 'loans.') && str_ends_with((string) $key, '.max_salary_multiplier')) {
            return ['value' => ['required', 'numeric', 'min:0.1', 'max:24']];
        }
        if (str_starts_with((string) $key, 'purchasing.supplier_score.weight_')) {
            return ['value' => ['required', 'numeric', 'min:0', 'max:1']];
        }
        $policyRules = [
            'tax.ph.vat_rate' => ['value' => ['required', 'numeric', 'min:0', 'max:1']],
            'payroll.anomaly.net_change_ratio' => ['value' => ['required', 'numeric', 'min:0', 'max:5']],
            'payroll.anomaly.overtime_hours' => ['value' => ['required', 'numeric', 'min:0', 'max:500']],
            'payroll.anomaly.deduction_ratio' => ['value' => ['required', 'numeric', 'min:0', 'max:1']],
            'mrp.safety_buffer_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'mrp.default_lead_time_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'mrp.schedule.default_horizon_days' => ['value' => ['required', 'integer', 'min:0', 'max:3650']],
            'approval.po.vp_threshold' => ['value' => ['required', 'numeric', 'min:0', 'max:1000000000000']],
            'attendance.auto_ot_detect.threshold_minutes' => ['value' => ['required', 'integer', 'min:0', 'max:1440']],
            'inventory.safety_stock.history_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'inventory.safety_stock.min_demand_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'inventory.safety_stock.service_level_z' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'inventory.abc.history_months' => ['value' => ['required', 'integer', 'min:1', 'max:120']],
            'calendar.max_range_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'hr.onboarding.stale_days' => ['value' => ['required', 'integer', 'min:1', 'max:365']],
            'hr.probation.period_months' => ['value' => ['required', 'integer', 'min:1', 'max:60']],
            'production.dashboard.defect_history_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'loans.max_pay_periods' => ['value' => ['required', 'integer', 'min:1', 'max:120']],
            'sales.default_customer_payment_terms_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'purchasing.default_vendor_payment_terms_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'sales.default_delivery_lead_days' => ['value' => ['required', 'integer', 'min:0', 'max:3650']],
            'approvals.reminder_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'approvals.escalation_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'approvals.recent_history_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'approvals.auto_resolve.enabled' => ['value' => ['required', 'boolean']],
            'approvals.auto_resolve.default_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'approvals.auto_resolve.default_action' => ['value' => ['required', 'in:approve,reject,escalate']],
            'dashboard.kpi_snapshot_lookback_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'dashboard.badges.cache_ttl_seconds' => ['value' => ['required', 'integer', 'min:1', 'max:86400']],
            'dashboard.badges.danger_threshold' => ['value' => ['required', 'integer', 'min:0', 'max:1000000']],
            'dashboard.badges.warning_threshold' => ['value' => ['required', 'integer', 'min:0', 'max:1000000']],
            'dashboard.admin.pending_jobs_warning_threshold' => ['value' => ['required', 'integer', 'min:0', 'max:1000000']],
            'self_service.history_limit' => ['value' => ['required', 'integer', 'min:1', 'max:500']],
            'forecasting.trend_slope_ratio' => ['value' => ['required', 'numeric', 'min:0', 'max:1']],
            'forecasting.trend_minimum_slope' => ['value' => ['required', 'numeric', 'min:0', 'max:1000000']],
            'mrp.work_order.urgent_delivery_days' => ['value' => ['required', 'integer', 'min:0', 'max:3650']],
            'mrp.work_order.urgent_priority' => ['value' => ['required', 'integer', 'min:0', 'max:255']],
            'mrp.work_order.normal_priority' => ['value' => ['required', 'integer', 'min:0', 'max:255']],
            'alerts.dedup_window_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'alerts.mold.warning_ratio' => ['value' => ['required', 'numeric', 'min:0', 'max:1']],
            'alerts.mold.critical_ratio' => ['value' => ['required', 'numeric', 'min:0', 'max:1']],
            'alerts.oee.quality_rate_threshold' => ['value' => ['required', 'numeric', 'min:0', 'max:1']],
            'alerts.oee.lookback_days' => ['value' => ['required', 'integer', 'min:1', 'max:365']],
            'alerts.oee.minimum_output_count' => ['value' => ['required', 'integer', 'min:1']],
            'alerts.ar.warning_overdue_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'alerts.ar.critical_overdue_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'alerts.ap.due_soon_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'alerts.quality.scrap_rate_threshold' => ['value' => ['required', 'numeric', 'min:0', 'max:1']],
            'alerts.quality.lookback_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'alerts.quality.minimum_output_count' => ['value' => ['required', 'integer', 'min:1']],
            'security.auth_history_window_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'accounting.customer_credit.warning_ratio' => ['value' => ['required', 'numeric', 'gt:0', 'lte:1']],
            'leave.calendar.coverage_success_pct' => ['value' => ['required', 'numeric', 'min:0', 'max:100']],
            'leave.calendar.coverage_warning_pct' => ['value' => ['required', 'numeric', 'min:0', 'max:100']],
            'leave.balance.display_warning_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'leave.balance.display_critical_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'quality.effectiveness.check_interval_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'quality.effectiveness.overdue_escalation_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'quality.effectiveness.overdue_notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'quality.calibration.due_window_days' => ['value' => ['required', 'integer', 'min:0', 'max:3650']],
            'quality.ncr.recurrence_window_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'quality.document_review.rearm_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'quality.document_review.recipient_roles' => ['value' => ['required', 'array', 'min:1']],
            'payroll.work_days_per_month' => ['value' => ['required', 'numeric', 'gt:0', 'max:31']],
            'payroll.hours_per_day' => ['value' => ['required', 'numeric', 'gt:0', 'max:24']],
            'payroll.overtime.ordinary_multiplier' => ['value' => ['required', 'numeric', 'min:1', 'max:10']],
            'payroll.overtime.premium_day_multiplier' => ['value' => ['required', 'numeric', 'min:1', 'max:10']],
            'payroll.night_differential_rate' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'payroll.pagibig.compensation_ceiling' => ['value' => ['required', 'numeric', 'gt:0']],
            // Floor of 31 keeps this above ProcessPayrollJob's 30-minute
            // timeout — below that a healthy run could be reclaimed mid-batch.
            // PayrollPeriodService::staleAfterMinutes() enforces the same floor
            // at read time, so an older out-of-range row degrades safely too.
            'payroll.compute.stale_after_minutes' => ['value' => ['required', 'integer', 'min:31', 'max:1440']],
            'payroll.bank_file.default_format' => ['value' => ['required', 'string', 'max:30']],
            'payroll.thirteenth_month.default_pay_day' => ['value' => ['required', 'integer', 'between:1,31']],
            'fiscal.year_start_month' => ['value' => ['required', 'integer', 'between:1,12']],
            'accounting.ar_dunning.enabled' => ['value' => ['required', 'boolean']],
            'accounting.ar_dunning.tier_days_csv' => ['value' => ['required', 'regex:/^\d+(,\d+)*$/']],
            'accounting.default_sales_revenue_account_code' => ['value' => ['required', 'string', 'max:20']],
            'hr.auto_provision_user.enabled' => ['value' => ['required', 'boolean']],
            'payroll.payslip_email.enabled' => ['value' => ['required', 'boolean']],
            'purchasing.supplier_score.neutral_missing_metric' => ['value' => ['required', 'numeric', 'between:0,100']],
            'purchasing.supplier_score.ncr_penalty_factor' => ['value' => ['required', 'numeric', 'min:0']],
            'purchasing.supplier_score.price_penalty_factor' => ['value' => ['required', 'numeric', 'min:0']],
            'purchasing.supplier_score.lead_time_penalty_factor' => ['value' => ['required', 'numeric', 'min:0']],
            'purchasing.supplier_score.tier_a_min' => ['value' => ['required', 'numeric', 'between:0,100']],
            'purchasing.supplier_score.tier_b_min' => ['value' => ['required', 'numeric', 'between:0,100']],
            'purchasing.supplier_score.tier_c_min' => ['value' => ['required', 'numeric', 'between:0,100']],
            'purchasing.supplier_score.deterioration_drop' => ['value' => ['required', 'numeric', 'between:0,100']],
            'purchasing.supplier_score.on_time_target' => ['value' => ['required', 'numeric', 'between:0,100']],
            'purchasing.supplier_score.quality_target' => ['value' => ['required', 'numeric', 'between:0,100']],
            'purchasing.supplier_score.price_variance_target' => ['value' => ['required', 'numeric', 'min:0']],
            'purchasing.supplier_score.lead_time_variance_target' => ['value' => ['required', 'numeric', 'min:0']],
            'purchasing.supplier_score.trend_months' => ['value' => ['required', 'integer', 'min:1', 'max:36']],
            'hr.training_expiry.t30_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'hr.training_expiry.t14_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'hr.training_expiry.t7_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'quality.ncr.sla_critical_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'quality.ncr.sla_high_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'quality.ncr.sla_medium_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'quality.ncr.sla_low_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'quality.ncr.escalation_roles' => ['value' => ['required', 'array', 'size:3']],
            'quality.ncr.escalation_subjects' => ['value' => ['required', 'array', 'size:3']],
            'quality.ncr.default_disposition' => ['value' => ['required', 'string', 'max:30']],
            'quality.ncr.auto_created_notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'quality.ncr.recurrence_notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'quality.ppap.approval_validity_years' => ['value' => ['required', 'integer', 'min:1', 'max:100']],
            'crm.complaint_8d.d3_due_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'crm.complaint_8d.d4_due_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'crm.complaint_8d.finalize_due_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'crm.complaint_8d.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'crm.complaint_8d.escalation_subjects' => ['value' => ['required', 'array', 'min:3']],
            'attendance.ot.minimum_minutes' => ['value' => ['required', 'integer', 'min:0', 'max:1440']],
            'attendance.ot.maximum_minutes' => ['value' => ['required', 'integer', 'min:1', 'max:1440']],
            'attendance.ot.request_min_hours' => ['value' => ['required', 'numeric', 'gt:0', 'max:24']],
            'attendance.ot.request_max_hours' => ['value' => ['required', 'numeric', 'gt:0', 'max:24']],
            'attendance.ot.admin_max_hours' => ['value' => ['required', 'numeric', 'gt:0', 'max:24']],
            'attendance.ot.request_future_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'attendance.ot.request_past_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'attendance.tardiness.maximum_minutes' => ['value' => ['required', 'integer', 'min:1', 'max:1440']],
            'attendance.night_band_start_hour' => ['value' => ['required', 'integer', 'between:0,23']],
            'attendance.night_band_end_hour' => ['value' => ['required', 'integer', 'between:0,23']],
            'attendance.half_day_work_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'payroll.day_rate.regular_holiday' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'payroll.day_rate.regular_holiday_rest_day' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'payroll.day_rate.special_holiday' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'payroll.day_rate.special_holiday_rest_day' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'payroll.day_rate.rest_day' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'payroll.de_minimis.rice_subsidy.monthly_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'payroll.de_minimis.uniform_allowance.monthly_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'payroll.de_minimis.uniform_allowance.annual_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'payroll.de_minimis.medical_cash_allowance.monthly_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'payroll.de_minimis.laundry_allowance.monthly_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'payroll.de_minimis.employee_achievement_award.monthly_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'payroll.de_minimis.employee_achievement_award.annual_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'payroll.de_minimis.gifts.monthly_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'payroll.de_minimis.gifts.annual_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'payroll.de_minimis.meal_allowance_per_ot.monthly_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'budget.warning_ratio' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'budget.critical_ratio' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'budget.exhausted_ratio' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'budget.overdrawn_ratio' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'inventory.abc.a_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'inventory.abc.b_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'inventory.replenishment.demand_history_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'inventory.replenishment.coverage_buffer_ratio' => ['value' => ['required', 'numeric', 'gt:0', 'max:10']],
            'inventory.stockout.demand_history_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'inventory.stockout.forecast_period_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'inventory.stockout.coverage_buffer_ratio' => ['value' => ['required', 'numeric', 'gt:0', 'max:10']],
            'inventory.stockout.zero_lead_reorder_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'inventory.stockout.high_risk_buffer_days' => ['value' => ['required', 'integer', 'min:0', 'max:3650']],
            'inventory.stockout.medium_risk_days' => ['value' => ['required', 'integer', 'min:0', 'max:3650']],
            'inventory.stockout.default_horizon_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'inventory.stock_count.default_scope' => ['value' => ['required', 'string', 'max:30']],
            'inventory.grn.default_qc_result' => ['value' => ['required', 'string', 'max:30']],
            'inventory.stockout.minimum_horizon_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'inventory.stockout.maximum_horizon_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'forecasting.default_history_months' => ['value' => ['required', 'integer', 'min:3', 'max:36']],
            'forecasting.default_horizon_months' => ['value' => ['required', 'integer', 'min:1', 'max:12']],
            'forecasting.accuracy.excellent_mape' => ['value' => ['required', 'numeric', 'min:0']],
            'forecasting.accuracy.acceptable_mape' => ['value' => ['required', 'numeric', 'min:0']],
            'forecasting.default_lookback_months' => ['value' => ['required', 'integer', 'min:3', 'max:24']],
            'forecasting.methods' => ['value' => ['required', 'array', 'min:1']],
            'forecasting.minimum_horizon_months' => ['value' => ['required', 'integer', 'min:1', 'max:36']],
            'forecasting.maximum_horizon_months' => ['value' => ['required', 'integer', 'min:1', 'max:36']],
            'forecasting.minimum_lookback_months' => ['value' => ['required', 'integer', 'min:1', 'max:36']],
            'forecasting.maximum_lookback_months' => ['value' => ['required', 'integer', 'min:1', 'max:60']],
            'returns.reason_codes' => ['value' => ['required', 'array']],
            'returns.resolutions' => ['value' => ['required', 'array']],
            'returns.item_conditions' => ['value' => ['required', 'array']],
            'quality.spc.cpk_launch_threshold' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'quality.spc.cpk_ongoing_threshold' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'quality.spc.cpk_action_threshold' => ['value' => ['required', 'numeric', 'min:0', 'max:10']],
            'quality.spc.minimum_capability_samples' => ['value' => ['required', 'integer', 'min:2', 'max:1000']],
            'mrp.mold.cost_trend_default_months' => ['value' => ['required', 'integer', 'min:1', 'max:36']],
            'quality.document.categories' => ['value' => ['required', 'array', 'min:1']],
            'quality.document.max_review_interval_months' => ['value' => ['required', 'integer', 'min:1', 'max:600']],
            'crm.opportunity.initial_probability' => ['value' => ['required', 'integer', 'min:0', 'max:100']],
            'documents.sequence_config' => ['value' => ['required', 'array', 'min:1']],
            'inventory.low_stock.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'purchasing.auto_po.approval_roles' => ['value' => ['required', 'array', 'min:1']],
            'production.work_order_completed.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'maintenance.machine_breakdown.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'crm.sales_order_confirmed.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'hr.separation.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'hr.recruitment.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'quality.outgoing_qc_delivery.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'quality.outgoing_qc.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'quality.in_process_qc.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'quality.inspection_failed.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'production.summary.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'inventory.grn_received.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'accounting.delivery_confirmed.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'purchasing.purchase_request_approved.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'purchasing.purchase_order_approved.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'purchasing.purchase_request.default_priority' => ['value' => ['required', 'string', 'max:20']],
            'attendance.overtime_submitted.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'leave.pending_hr.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'leave.submitted.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'loans.submitted.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'purchasing.supplier_score.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'quality.incoming_qc.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'quality.grn_qc_failure.actor_roles' => ['value' => ['required', 'array', 'min:1']],
            'system.automation.actor_roles' => ['value' => ['required', 'array', 'min:1']],
            'landing.oem_partners' => ['value' => ['required', 'array', 'min:1']],
            'landing.quality_methods' => ['value' => ['required', 'array', 'min:1']],
            'landing.trust_points' => ['value' => ['required', 'array', 'min:1']],
            'landing.philippines_points' => ['value' => ['required', 'array', 'min:1']],
            'landing.stats' => ['value' => ['required', 'array', 'min:1']],
            'landing.capabilities' => ['value' => ['required', 'array', 'min:1']],
            'landing.process_steps' => ['value' => ['required', 'array', 'min:1']],
            'landing.quality_pillars' => ['value' => ['required', 'array', 'min:1']],
            'landing.quality_policy' => ['value' => ['required', 'array', 'min:1']],
            'landing.quality_policy.effective_date' => ['value' => ['required', 'string', 'max:100']],
            'landing.part_specs' => ['value' => ['required', 'array', 'min:1']],
            'landing.quality_policy.objectives' => ['value' => ['required', 'array', 'min:1']],
            'landing.philippines_copy' => ['value' => ['required', 'array', 'min:1']],
            'landing.hero_copy' => ['value' => ['required', 'array', 'min:1']],
            'dashboard.widgets.leave_calendar_horizon_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'dashboard.widgets.ap_due_horizon_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'production.dashboard.mold_warning_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'action_center.default_sla_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'dashboard.action_center.source_limit' => ['value' => ['required', 'integer', 'min:1', 'max:500']],
            'dashboard.action_center.max_items' => ['value' => ['required', 'integer', 'min:1', 'max:1000']],
            'dashboard.chain_bottlenecks.result_limit' => ['value' => ['required', 'integer', 'min:1', 'max:500']],
            'action_center.maintenance.critical_sla_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'action_center.maintenance.default_sla_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'maintenance.work_order.default_type' => ['value' => ['required', 'string', 'max:30']],
            'maintenance.work_order.default_priority' => ['value' => ['required', 'string', 'max:30']],
            'action_center.production.critical_sla_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'action_center.production.default_sla_hours' => ['value' => ['required', 'integer', 'min:1', 'max:8760']],
            'accounting.accounts.ar_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.ap_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.vat_output_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.vat_input_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.discount_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.grni_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.inventory_raw_material_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.inventory_finished_goods_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.inventory_packaging_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.inventory_spare_parts_code' => ['value' => ['required', 'string', 'max:20']],
            'quality.rollout.fixed_sample_size' => ['value' => ['required', 'integer', 'min:1', 'max:1000']],
            'quality.aql.default_level' => ['value' => ['required', 'string', 'max:20']],
            'quality.rollout.eligible_item_types' => ['value' => ['required', 'array', 'min:1']],
            'quality.rollout.template.resin' => ['value' => ['required', 'array', 'min:1']],
            'quality.rollout.template.general' => ['value' => ['required', 'array', 'min:1']],
            'quality.dashboard.defect_history_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'approval.pr.dept_head_auto_approve_threshold' => ['value' => ['required', 'numeric', 'min:0']],
            'accounting.default_expense_account_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.final_pay_salary_expense_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.cash_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.loans_payable_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.accrued_expense_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.asset_cash_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.asset_accumulated_depreciation_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.asset_cost_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.asset_disposal_loss_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.asset_disposal_gain_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.depreciation_expense_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.sss_payable_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.philhealth_payable_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.pagibig_payable_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.withholding_tax_payable_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.thirteenth_month_payable_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.salary_expense_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.overtime_expense_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.thirteenth_month_expense_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.sss_employer_expense_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.philhealth_employer_expense_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.pagibig_employer_expense_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.accounts.payroll_cash_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.statements.current_period_net_income_code' => ['value' => ['required', 'string', 'max:20']],
            'accounting.statements.translation_adjustment_code' => ['value' => ['required', 'string', 'max:20']],
            'purchasing.urgent_skip_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'budgeting.enforcement_mode' => ['value' => ['required', 'in:off,warn,block']],
            'accounting.je_self_post_limit' => ['value' => ['required', 'numeric', 'min:0']],
            'inventory.adjustment_approval_threshold' => ['value' => ['required', 'numeric', 'min:0']],
            'inventory.over_receipt_tolerance_pct' => ['value' => ['required', 'numeric', 'min:0', 'max:100']],
            'quality.ncr.replacement_work_order_lead_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'quality.ncr.replacement_work_order_priority' => ['value' => ['required', 'integer', 'between:0,10']],
            'quality.ppap_gate_enabled' => ['value' => ['required', 'boolean']],
            'company.employee_email_domain' => ['value' => ['required', 'string', 'max:255']],
            'company.sales_inbox_email' => ['value' => ['required', 'email', 'max:255']],
            'hr.default_user_role_slug' => ['value' => ['required', 'string', 'max:100']],
            'hr.self_service.certificate_catalog' => ['value' => ['required', 'array', 'min:1']],
            'accounting.functional_currency_code' => ['value' => ['required', 'string', 'size:3']],
            'accounting.reporting_currency_code' => ['value' => ['required', 'string', 'size:3']],
            'dashboard.widgets.gantt_horizon_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'dashboard.widgets.payables_horizon_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'dashboard.widgets.probation_horizon_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'dashboard.widgets.delivery_horizon_days' => ['value' => ['required', 'integer', 'min:0', 'max:365']],
            'inventory.dashboard.consumption_history_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'inventory.stock_count.variance_tolerance_pct' => ['value' => ['required', 'numeric', 'min:0', 'max:100']],
            'inventory.dashboard.zone_utilization_warning_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'inventory.dashboard.zone_utilization_critical_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'dashboard.finance.payroll_pipeline_history_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'dashboard.chain_bottlenecks' => ['value' => ['required', 'array', 'min:1']],
            'maintenance.downtime.default_history_days' => ['value' => ['required', 'integer', 'min:1', 'max:3650']],
            'maintenance.downtime.availability_good_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'maintenance.downtime.availability_warning_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'maintenance.downtime.total_warning_minutes' => ['value' => ['required', 'integer', 'min:1', 'max:100000']],
            'maintenance.downtime.mtbf_good_hours' => ['value' => ['required', 'numeric', 'min:0', 'max:100000']],
            'maintenance.downtime.mttr_good_minutes' => ['value' => ['required', 'numeric', 'min:0', 'max:100000']],
            'maintenance.downtime.breakdown_warning_count' => ['value' => ['required', 'integer', 'min:1', 'max:100000']],
            'maintenance.downtime.breakdown_critical_count' => ['value' => ['required', 'integer', 'min:1', 'max:100000']],
            'production.oee.world_class_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'production.oee.on_track_ratio' => ['value' => ['required', 'numeric', 'between:0,1']],
            'quality.dashboard.defect_danger_pct' => ['value' => ['required', 'numeric', 'between:0,100']],
            'quality.dashboard.defect_warning_pct' => ['value' => ['required', 'numeric', 'between:0,100']],
            'quality.dashboard.coverage_success_pct' => ['value' => ['required', 'numeric', 'between:0,100']],
            'quality.dashboard.coverage_info_pct' => ['value' => ['required', 'numeric', 'between:0,100']],
            'quality.dashboard.coverage_warning_pct' => ['value' => ['required', 'numeric', 'between:0,100']],
            'leave.request.past_window_days' => ['value' => ['required', 'integer', 'min:0', 'max:3650']],
            'leave.request.future_window_days' => ['value' => ['required', 'integer', 'min:0', 'max:3650']],
            'inventory.safety_stock.issue_movement_types' => ['value' => ['required', 'array', 'min:1']],
            'quality.aql.sample_plan' => ['value' => ['required', 'array']],
            'mrp.bom.max_explode_depth' => ['value' => ['required', 'integer', 'min:1', 'max:100']],
            'landing.section_copy' => ['value' => ['required', 'array']],
            'notifications.catalog' => ['value' => ['required', 'array', 'min:1']],
            'system_user.email' => ['value' => ['required', 'email', 'max:255']],
            'system_user.name' => ['value' => ['required', 'string', 'max:255']],
            'leave.year_end.automation_user_email' => ['value' => ['required', 'email', 'max:255']],
            'maintenance.mold_schedule.trigger_threshold_pct' => ['value' => ['required', 'numeric', 'between:0,100']],
            'approvals.escalation.superior_role_map' => ['value' => ['required', 'array', 'min:1']],
            'alerts.critical.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'mrp.daily_run.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'hr.training_expiry.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'quality.ncr.return_to_supplier.notification_roles' => ['value' => ['required', 'array', 'min:1']],
            'exports.default_time_of_day' => ['value' => ['required', 'date_format:H:i']],
            'workflow.chain_definitions' => ['value' => ['required', 'array', 'min:1']],
        ];

        return $securityRules[$key] ?? $maintenanceRules[$key] ?? $policyRules[$key] ?? $base;
    }

    public function messages(): array
    {
        return [
            'value.min' => 'Value is below the allowed minimum.',
            'value.max' => 'Value exceeds the allowed maximum.',
        ];
    }
}
