{{-- Sprint P9 — Purchase Request PDF.

     Mirrors purchase-order.blade.php structure. Items column shows
     description / quantity / estimated unit price / estimated total.
     Approvals come from the shared ApprovalSignatureBuilder. --}}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{{ $pr->pr_number }}</title>
<style>
    body { font-family: 'DejaVu Sans', sans-serif; font-size: 11px; color: #111; }
    h1 { font-size: 14px; margin: 0 0 8px; }
    .muted { color: #666; }
    .right { text-align: right; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 6px 8px; vertical-align: top; }
    .header { display: table; width: 100%; margin-bottom: 16px; }
    .header > div { display: table-cell; vertical-align: top; }
    .header .right { text-align: right; }
    .lines th, .lines td { border-bottom: 0.5px solid #ddd; }
    .lines th { font-size: 9px; text-transform: uppercase; letter-spacing: 0.04em; color: #666; text-align: left; border-bottom: 1px solid #999; }
    .lines td.num { font-family: 'DejaVu Sans Mono', monospace; text-align: right; }
    .totals { margin-top: 12px; width: 320px; margin-left: auto; }
    .totals td { padding: 3px 6px; font-family: 'DejaVu Sans Mono', monospace; }
    .totals .label { color: #666; text-align: right; }
    .totals .amt { text-align: right; }
    .totals .total { border-top: 1px solid #999; font-weight: bold; }
    .footer { margin-top: 30px; font-size: 9px; color: #888; text-align: center; }
    .priority-urgent { background: #FEF3C7; color: #92400E; padding: 2px 6px; border-radius: 3px; font-weight: bold; }
    .priority-critical { background: #FEE2E2; color: #991B1B; padding: 2px 6px; border-radius: 3px; font-weight: bold; }
</style>
</head>
<body>

<div class="header">
    <div>
        <h1>{{ $company['name'] }}</h1>
        <div class="muted">{{ $company['address'] }}</div>
        @if($company['tin']) <div class="muted">TIN: {{ $company['tin'] }}</div> @endif
    </div>
    <div class="right">
        <h1>PURCHASE REQUEST</h1>
        <div><strong>{{ $pr->pr_number }}</strong></div>
        <div class="muted">Date: {{ optional($pr->date)->format('M d, Y') }}</div>
        @if($pr->priority?->value === 'urgent')
            <div><span class="priority-urgent">URGENT</span></div>
        @elseif($pr->priority?->value === 'critical')
            <div><span class="priority-critical">CRITICAL</span></div>
        @endif
    </div>
</div>

<table>
    <tr>
        <td style="width:50%; padding-right:16px;">
            <div class="muted" style="font-size:9px;">REQUESTED BY</div>
            <div><strong>{{ $pr->requester?->name ?? '—' }}</strong></div>
            @if($pr->department)
                <div class="muted">{{ $pr->department->name }} ({{ $pr->department->code }})</div>
            @endif
        </td>
        <td style="width:50%;">
            <div class="muted" style="font-size:9px;">STATUS</div>
            <div>{{ str_replace('_', ' ', strtoupper((string) $pr->status?->value)) }}</div>
            @if($pr->is_auto_generated)
                <div class="muted" style="margin-top:4px; font-size:9px;">Auto-generated by MRP / low-stock automation</div>
            @endif
        </td>
    </tr>
</table>

@if($pr->reason)
    <div style="margin-top:14px; font-size:10px;">
        <div class="muted" style="font-size:9px; text-transform:uppercase; letter-spacing:0.04em;">REASON</div>
        <div>{{ $pr->reason }}</div>
    </div>
@endif

<table class="lines" style="margin-top:14px;">
    <thead><tr>
        <th style="width:30px;">#</th>
        <th>Item</th>
        <th>Description</th>
        <th class="right">Qty</th>
        <th class="right">Est. Unit Price</th>
        <th class="right">Est. Total</th>
        <th>Purpose</th>
    </tr></thead>
    <tbody>
    @foreach($pr->items as $i => $line)
        <tr>
            <td>{{ $i + 1 }}</td>
            <td>{{ $line->item?->code ?? '—' }}</td>
            <td>{{ $line->description }}</td>
            <td class="num">
                {{ number_format((float) $line->quantity, 2) }} {{ $line->unit }}
            </td>
            <td class="num">
                @if($line->estimated_unit_price !== null)
                    {{ number_format((float) $line->estimated_unit_price, 2) }}
                @else —
                @endif
            </td>
            <td class="num">{{ number_format((float) $line->estimated_total, 2) }}</td>
            <td class="muted" style="font-size:10px;">{{ $line->purpose ?? '—' }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<table class="totals">
    <tr class="total">
        <td class="label">Total Estimated (PHP)</td>
        <td class="amt">{{ number_format((float) $pr->total_estimated_amount, 2) }}</td>
    </tr>
</table>

@include('pdf._components.approval_signatures', ['approvals' => $approvals])

<div class="footer">
    Generated on {{ $now->format('M d, Y · H:i') }} ·
    {{ $company['name'] }} · OGAMI ERP
</div>

</body>
</html>
