<?php

declare(strict_types=1);

namespace App\Common\Services;

use App\Common\Exceptions\BusinessRuleException;
use App\Common\Enums\DocumentType;
use App\Common\Models\Document;
use App\Modules\Auth\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use RuntimeException;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Series E (Task E3) — central vault for every system-generated PDF.
 * Every per-document PDF service routes through this so:
 *   1. The blob is persisted to private storage (never web-root).
 *   2. A `documents` row is inserted (audit trail).
 *   3. Preview / download / email all share one resource model.
 *
 * Direct DomPDF Pdf::loadView()->stream() outside of this service is a
 * code-review red flag — the byte never reaches the audit log.
 */
class DocumentVaultService
{
    /** Disk used for private blobs. Defaults to Laravel's `local` disk. */
    private const DISK = 'local';

    /**
     * Persist generated bytes and return the vault row.
     *
     * @param  string  $bytes  Raw PDF bytes
     * @param  Model  $entity  Owning record
     * @param  User|null  $user  Generator (null for system jobs)
     * @param  bool|null  $confidential  Override the type's default
     */
    public function store(
        string $bytes,
        DocumentType $type,
        Model $entity,
        ?User $user = null,
        ?bool $confidential = null,
    ): Document {
        if ($bytes === '') {
            throw new BusinessRuleException('Refusing to store an empty document.');
        }

        $confidential ??= $type->isConfidential();
        $entityRef = $this->entityRef($entity);

        $filename = sprintf(
            '%s-%s-%s-%s.pdf',
            $type->value,
            $entityRef,
            now()->format('YmdHis'),
            Str::lower(Str::random(6)),
        );
        $path = sprintf('documents/%s/%s', $type->value, $filename);

        if (! Storage::disk(self::DISK)->put($path, $bytes)) {
            throw new BusinessRuleException('Unable to store document bytes.');
        }

        try {
            return DB::transaction(fn () => Document::create([
                'document_type' => $type,
                'entity_type' => $entity::class,
                'entity_id' => $entity->getKey(),
                'file_path' => $path,
                'file_name' => $filename,
                'file_size' => strlen($bytes),
                'mime_type' => 'application/pdf',
                'generated_by' => $user?->id,
                'generated_at' => now(),
                'is_confidential' => $confidential,
                'checksum_sha256' => hash('sha256', $bytes),
            ]));
        } catch (\Throwable $e) {
            Storage::disk(self::DISK)->delete($path);
            throw $e;
        }
    }

    /**
     * Replace an existing vault row's blob (e.g. regenerate after data fix).
     * The new row is written first, then the old blob is purged so we never
     * lose data on partial failure.
     *
     * The new row reuses the original `entity_type` + `entity_id` directly
     * so we don't need to resolve the morphTo relation — that lets us
     * regenerate even when the underlying entity has been soft-deleted, and
     * keeps tests happy when fixtures use anonymous models.
     */
    public function regenerate(Document $existing, string $bytes, ?User $user = null): Document
    {
        if ($bytes === '') {
            throw new RuntimeException('Refusing to regenerate with empty bytes.');
        }

        $type = $existing->document_type;
        if (! $type instanceof DocumentType) {
            throw new RuntimeException('Existing document has an unknown type.');
        }

        $entityRef = $existing->entity_id !== null ? 'rec-'.$existing->entity_id : 'rec';
        $filename = sprintf(
            '%s-%s-%s-%s.pdf',
            $type->value,
            $entityRef,
            now()->format('YmdHis'),
            Str::lower(Str::random(6)),
        );
        $path = sprintf('documents/%s/%s', $type->value, $filename);

        if (! Storage::disk(self::DISK)->put($path, $bytes)) {
            throw new RuntimeException('Unable to store regenerated document bytes.');
        }

        $oldPath = $existing->file_path;
        try {
            return DB::transaction(function () use ($bytes, $type, $existing, $user, $path, $filename, $oldPath) {
                $fresh = Document::create([
                    'document_type' => $type,
                    'entity_type' => $existing->entity_type,
                    'entity_id' => $existing->entity_id,
                    'file_path' => $path,
                    'file_name' => $filename,
                    'file_size' => strlen($bytes),
                    'mime_type' => 'application/pdf',
                    'generated_by' => $user?->id,
                    'generated_at' => now(),
                    'is_confidential' => (bool) $existing->is_confidential,
                    'checksum_sha256' => hash('sha256', $bytes),
                ]);

                $existing->delete();
                DB::afterCommit(function () use ($oldPath): void {
                    if ($oldPath) {
                        Storage::disk(self::DISK)->delete($oldPath);
                    }
                });

                return $fresh;
            });
        } catch (\Throwable $e) {
            Storage::disk(self::DISK)->delete($path);
            throw $e;
        }
    }

    /** Stream a vault row inline (browser preview iframe). */
    public function streamInline(Document $doc): StreamedResponse
    {
        return $this->stream($doc, 'inline');
    }

    /** Stream a vault row as an attachment (download). */
    public function streamDownload(Document $doc): StreamedResponse
    {
        return $this->stream($doc, 'attachment');
    }

    public function delete(Document $doc): void
    {
        $path = $doc->file_path;
        DB::transaction(function () use ($doc, $path) {
            $doc->delete();
            DB::afterCommit(function () use ($path): void {
                if ($path) {
                    Storage::disk(self::DISK)->delete($path);
                }
            });
        });
    }

    /** @return Collection<int, Document> */
    public function listForEntity(Model $entity): Collection
    {
        return Document::query()
            ->forEntity($entity)
            ->with('generatedBy:id,name')
            ->orderByDesc('generated_at')
            ->get();
    }

    /** Read raw bytes — used by Mailable attachments. */
    public function readBytes(Document $doc): string
    {
        $contents = Storage::disk(self::DISK)->get($doc->file_path);
        if ($contents === null || $contents === false) {
            throw new RuntimeException("Vault blob missing: {$doc->file_path}");
        }

        return (string) $contents;
    }

    private function stream(Document $doc, string $disposition): StreamedResponse
    {
        // A vault row whose blob has been pruned/lost is a missing resource,
        // not a server fault — let readBytes() keep throwing for the mail
        // attachment path, but answer HTTP callers with a 404.
        try {
            $bytes = $this->readBytes($doc);
        } catch (RuntimeException) {
            abort(404, 'This document is no longer available.');
        }
        $headers = [
            'Content-Type' => $doc->mime_type ?: 'application/pdf',
            'Content-Length' => (string) strlen($bytes),
            'Content-Disposition' => sprintf(
                '%s; filename="%s"',
                $disposition,
                str_replace('"', '', $doc->file_name),
            ),
        ];

        if ($doc->is_confidential) {
            // Don't let the browser keep confidential PDFs in disk cache.
            $headers['Cache-Control'] = 'private, no-store, max-age=0, must-revalidate';
            $headers['Pragma'] = 'no-cache';
            $headers['X-Content-Type-Options'] = 'nosniff';
        }

        return new StreamedResponse(fn () => print $bytes, 200, $headers);
    }

    private function entityRef(Model $entity): string
    {
        // Pick the most identifying short field if available.
        foreach (['employee_no', 'invoice_number', 'po_number', 'wo_number',
            'inspection_number', 'delivery_number', 'bill_number',
            'pr_number', 'je_number', 'reference_no', 'code'] as $col) {
            if (isset($entity->{$col}) && is_string($entity->{$col}) && $entity->{$col} !== '') {
                return preg_replace('/[^A-Za-z0-9_-]+/', '-', (string) $entity->{$col}) ?: 'rec';
            }
        }

        return 'rec-'.$entity->getKey();
    }
}
