<?php

declare(strict_types=1);

namespace App\Common\Services;

use App\Common\Enums\DocumentType;
use App\Common\Models\Document;
use App\Modules\Auth\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use RuntimeException;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Series E (Task E3) — central vault for every system-generated PDF.
 * Every per-document PDF service routes through this so:
 *   1. The blob is persisted to private storage (never web-root).
 *   2. A `documents` row is inserted (audit trail).
 *   3. Preview / download / email all share one resource model.
 *
 * Direct DomPDF Pdf::loadView()->stream() outside of this service is a
 * code-review red flag — the byte never reaches the audit log.
 */
class DocumentVaultService
{
    /** Disk used for private blobs. Defaults to Laravel's `local` disk. */
    private const DISK = 'local';

    /**
     * Persist generated bytes and return the vault row.
     *
     * @param  string         $bytes        Raw PDF bytes
     * @param  DocumentType   $type
     * @param  Model          $entity       Owning record
     * @param  User|null      $user         Generator (null for system jobs)
     * @param  bool|null      $confidential Override the type's default
     */
    public function store(
        string $bytes,
        DocumentType $type,
        Model $entity,
        ?User $user = null,
        ?bool $confidential = null,
    ): Document {
        if ($bytes === '') {
            throw new RuntimeException('Refusing to store an empty document.');
        }

        $confidential ??= $type->isConfidential();
        $entityRef = $this->entityRef($entity);

        $filename = sprintf(
            '%s-%s-%s-%s.pdf',
            $type->value,
            $entityRef,
            now()->format('YmdHis'),
            Str::lower(Str::random(6)),
        );
        $path = sprintf('documents/%s/%s', $type->value, $filename);

        return DB::transaction(function () use ($bytes, $type, $entity, $user, $confidential, $path, $filename) {
            Storage::disk(self::DISK)->put($path, $bytes);

            return Document::create([
                'document_type'    => $type,
                'entity_type'      => $entity::class,
                'entity_id'        => $entity->getKey(),
                'file_path'        => $path,
                'file_name'        => $filename,
                'file_size'        => strlen($bytes),
                'mime_type'        => 'application/pdf',
                'generated_by'     => $user?->id,
                'generated_at'     => now(),
                'is_confidential'  => $confidential,
                'checksum_sha256'  => hash('sha256', $bytes),
            ]);
        });
    }

    /**
     * Replace an existing vault row's blob (e.g. regenerate after data fix).
     * The new row is written first, then the old blob is purged so we never
     * lose data on partial failure.
     */
    public function regenerate(Document $existing, string $bytes, ?User $user = null): Document
    {
        $existing->loadMissing('entity');
        $entity = $existing->entity;
        if (! $entity instanceof Model) {
            throw new RuntimeException('Cannot regenerate a document whose entity has been deleted.');
        }

        $type = $existing->document_type;
        if (! $type instanceof DocumentType) {
            throw new RuntimeException('Existing document has an unknown type.');
        }

        $fresh = $this->store($bytes, $type, $entity, $user, $existing->is_confidential);

        // Soft-delete the old vault row + remove blob.
        DB::transaction(function () use ($existing) {
            $oldPath = $existing->file_path;
            $existing->delete(); // soft delete

            if ($oldPath && Storage::disk(self::DISK)->exists($oldPath)) {
                Storage::disk(self::DISK)->delete($oldPath);
            }
        });

        return $fresh;
    }

    /** Stream a vault row inline (browser preview iframe). */
    public function streamInline(Document $doc): StreamedResponse
    {
        return $this->stream($doc, 'inline');
    }

    /** Stream a vault row as an attachment (download). */
    public function streamDownload(Document $doc): StreamedResponse
    {
        return $this->stream($doc, 'attachment');
    }

    public function delete(Document $doc): void
    {
        $path = $doc->file_path;
        DB::transaction(function () use ($doc, $path) {
            $doc->delete();
            if ($path && Storage::disk(self::DISK)->exists($path)) {
                Storage::disk(self::DISK)->delete($path);
            }
        });
    }

    /** @return Collection<int, Document> */
    public function listForEntity(Model $entity): Collection
    {
        return Document::query()
            ->forEntity($entity)
            ->with('generatedBy:id,name')
            ->orderByDesc('generated_at')
            ->get();
    }

    /** Read raw bytes — used by Mailable attachments. */
    public function readBytes(Document $doc): string
    {
        $contents = Storage::disk(self::DISK)->get($doc->file_path);
        if ($contents === null || $contents === false) {
            throw new RuntimeException("Vault blob missing: {$doc->file_path}");
        }
        return (string) $contents;
    }

    private function stream(Document $doc, string $disposition): StreamedResponse
    {
        $bytes = $this->readBytes($doc);

        $headers = [
            'Content-Type'        => $doc->mime_type ?: 'application/pdf',
            'Content-Length'      => (string) strlen($bytes),
            'Content-Disposition' => sprintf(
                '%s; filename="%s"',
                $disposition,
                str_replace('"', '', $doc->file_name),
            ),
        ];

        if ($doc->is_confidential) {
            // Don't let the browser keep confidential PDFs in disk cache.
            $headers['Cache-Control'] = 'private, no-store, max-age=0, must-revalidate';
            $headers['Pragma']        = 'no-cache';
            $headers['X-Content-Type-Options'] = 'nosniff';
        }

        return response()->streamDownload(fn () => print $bytes, $doc->file_name, $headers);
    }

    private function entityRef(Model $entity): string
    {
        // Pick the most identifying short field if available.
        foreach (['employee_no', 'invoice_number', 'po_number', 'wo_number',
                  'inspection_number', 'delivery_note_number', 'bill_number',
                  'pr_number', 'je_number', 'reference_no', 'code'] as $col) {
            if (isset($entity->{$col}) && is_string($entity->{$col}) && $entity->{$col} !== '') {
                return preg_replace('/[^A-Za-z0-9_-]+/', '-', (string) $entity->{$col}) ?: 'rec';
            }
        }
        return 'rec-' . $entity->getKey();
    }
}
