#!/usr/bin/env bash
# Create a validated archive of private application uploads.
#
# The database dump and this archive are intentionally separate artifacts. The
# application source, .env, Redis cache, and Docker volumes are not included.

set -euo pipefail

: "${FILES_SOURCE_DIR:?FILES_SOURCE_DIR required}"
: "${BACKUP_DIR:=/backups}"
: "${BACKUP_KEEP:=14}"

case "${BACKUP_KEEP}" in
    ''|*[!0-9]*)
        echo "ERROR: BACKUP_KEEP must be a non-negative integer" >&2
        exit 2
        ;;
esac

if [ -z "${FILES_SOURCE_DIR}" ] || [ "${FILES_SOURCE_DIR}" = "/" ]; then
    echo "ERROR: refusing to archive an empty or root files directory" >&2
    exit 2
fi

mkdir -p "${FILES_SOURCE_DIR}" "${BACKUP_DIR}"

TS="$(date +%Y%m%d-%H%M%S)"
OUT="${BACKUP_DIR}/ogami-files-${TS}.tar.gz"
TMP="$(mktemp "${BACKUP_DIR}/.ogami-files-${TS}.XXXXXX")"

cleanup() {
    if [ -n "${TMP:-}" ]; then
        rm -f "${TMP}"
    fi
}
trap cleanup EXIT

if ! tar -czf "${TMP}" -C "${FILES_SOURCE_DIR}" .; then
    echo "ERROR: private files archive failed" >&2
    exit 1
fi

if ! [ -s "${TMP}" ] || ! gzip -t "${TMP}" || ! tar -tzf "${TMP}" >/dev/null; then
    echo "ERROR: private files archive is empty or corrupt" >&2
    exit 1
fi

mv -f "${TMP}" "${OUT}"
TMP=""
echo "files backup written: ${OUT} ($(du -h "${OUT}" | cut -f1))"

if [ -n "${BACKUP_S3_BUCKET:-}" ]; then
    command -v aws >/dev/null 2>&1 || {
        echo "ERROR: BACKUP_S3_BUCKET is set but 'aws' CLI is not installed" >&2
        exit 2
    }
    PREFIX="${BACKUP_S3_PREFIX:-}"
    if [ -n "${PREFIX}" ] && [ "${PREFIX%/}" = "${PREFIX}" ]; then
        PREFIX="${PREFIX}/"
    fi
    REMOTE="${BACKUP_S3_BUCKET%/}/${PREFIX}$(basename "${OUT}")"
    aws s3 cp "${OUT}" "${REMOTE}" --only-show-errors
    echo "off-site files copy ok"
fi

if [ "${BACKUP_KEEP}" -gt 0 ]; then
    # shellcheck disable=SC2012 — filenames are generated by this script.
    ls -1t "${BACKUP_DIR}"/ogami-files-*.tar.gz 2>/dev/null \
        | tail -n "+$((BACKUP_KEEP + 1))" \
        | xargs -r rm -f --
fi
