{{--
    Series E (E1) footer. The `script type="text/php"` block is read by
    DomPDF on render and writes "Page N of M" on every page. The plain
    div above it shows the disclaimer + generator metadata.
--}}
<div class="footer-meta" style="position:fixed; bottom:24px; left:0; right:0;
     text-align:center; font-size:7px; color:#999;
     padding:0 32px;">
  @if (!empty($company['disclaimer']))
    <div style="margin-bottom:2px;">{{ $company['disclaimer'] }}</div>
  @endif
  <div>
    Generated by {{ $generated['by'] ?? 'system' }}
    on {{ $generated['at_text'] ?? now()->format('M d, Y H:i') }}
    &middot; {{ $company['name'] ?? 'Ogami ERP' }}
  </div>
</div>

<script type="text/php">
  if (isset($pdf)) {
    $font = $fontMetrics->getFont('DejaVu Sans');
    $size = 7;
    // Bottom-right page number; layout is fixed at 8pt, A4 portrait default.
    $pdf->page_text(495, 815, "Page {PAGE_NUM} of {PAGE_COUNT}", $font, $size, [0.55, 0.55, 0.55]);
  }
</script>
