{{--
    Series E (E1) optional QR rendering. Requires the caller to pass a
    pre-rendered $qrSvg or $qrUrl. We intentionally do NOT pull
    simplesoftwareio/simple-qrcode here because DomPDF can't render SVG
    consistently — instead, callers can pass a public PNG path or a
    data URI generated by an upstream service. If neither is available,
    we fall back to a textual reference link the user can type.
--}}
@php
    $qrSvg = $qrSvg ?? null;
    $qrUrl = $qrUrl ?? null;
    $qrText = $qrText ?? null;
@endphp

@if (!empty($qrSvg))
  <div class="qr">{!! $qrSvg !!}</div>
@elseif (!empty($qrUrl))
  <div class="qr"><img src="{{ $qrUrl }}" alt="QR" style="width:64px; height:64px;"></div>
@elseif (!empty($qrText))
  <div class="qr-fallback" style="font-size:8px; color:#999;">
    Verify online:<br>{{ $qrText }}
  </div>
@endif
