<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Series E (Task E1) — seed company branding rows in the `settings` table
 * so every PDF letterhead reads from a single source. Idempotent: only
 * inserts keys that don't already exist (existing values are preserved).
 */
return new class extends Migration {
    public function up(): void
    {
        $defaults = [
            'company.legal_name'   => 'Philippine Ogami Corporation',
            'company.address'      => 'FCIE, Dasmariñas, Cavite, Philippines',
            'company.phone'        => '(046) 000-0000',
            'company.email'        => 'info@ogami.ph',
            'company.tin'          => '000-000-000-000',
            'company.vat_status'   => 'VAT Registered',
            'company.logo_path'    => '',
            // Used when generating self-service URLs in QR codes.
            'company.public_url'   => 'https://ogami.ph',
            // E1: shows on every PDF footer.
            'pdf.footer_disclaimer' => 'This document was system-generated by Ogami ERP and does not require a wet signature unless indicated.',
        ];

        $now = now();
        foreach ($defaults as $key => $value) {
            $exists = DB::table('settings')->where('key', $key)->exists();
            if ($exists) continue;

            DB::table('settings')->insert([
                'key'        => $key,
                'value'      => json_encode($value),
                'group'      => 'company',
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }

    public function down(): void
    {
        DB::table('settings')
            ->where('group', 'company')
            ->whereIn('key', [
                'company.legal_name', 'company.address', 'company.phone',
                'company.email', 'company.tin', 'company.vat_status',
                'company.logo_path', 'company.public_url',
                'pdf.footer_disclaimer',
            ])
            ->delete();
    }
};
