<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        $row = DB::table('settings')->where('key', 'pdf.footer_disclaimer')->first();
        if ($row && json_decode((string) $row->value, true) === 'This document was system-generated by Ogami ERP and does not require a wet signature unless indicated.') {
            DB::table('settings')->where('key', 'pdf.footer_disclaimer')->update([
                'value' => json_encode('This document was system-generated and does not require a wet signature unless indicated.'),
                'updated_at' => now(),
            ]);
        }
    }

    public function down(): void
    {
        $row = DB::table('settings')->where('key', 'pdf.footer_disclaimer')->first();
        if ($row && json_decode((string) $row->value, true) === 'This document was system-generated and does not require a wet signature unless indicated.') {
            DB::table('settings')->where('key', 'pdf.footer_disclaimer')->update([
                'value' => json_encode('This document was system-generated by Ogami ERP and does not require a wet signature unless indicated.'),
                'updated_at' => now(),
            ]);
        }
    }
};
